export const projects = [
    {
        id: 1,
        img: "https://drive.google.com/file/d/1XNQw4KFCsF1sJhFdQPKGQfCAEu7-3cno/view?usp=drive_link",
        title: "tinyLink",
        desc: "tinyLink is a web application that allows users to shorten long URLs, generate QR codes for the shortened URLs, and manage them easily.",
        stack: "ReactJs, NodeJs, ExpressJs, MongoDB",
        githubLink: "https://github.com/badalchowdhary/tinyLink",
        webLink: "https://tiny-link-client.vercel.app/",
    },
    {
        id: 2,
        img: "https://drive.google.com/file/d/1XNQw4KFCsF1sJhFdQPKGQfCAEu7-3cno/view?usp=drive_link",
        title: "Rentify",
        desc: "Rentify is a website which helps property owners to list their properties and find correct buyers and also helps buyers to find a property as per their requirement.",
        stack: "ReactJs, NodeJs, ExpressJs, MongoDB",
        githubLink: "https://github.com/badalchowdhary/Rentify",
        webLink: "https://rentify-frontend-badal-chowdharys-projects.vercel.app/",
    },
    {
        id: 3,
        img: "https://drive.google.com/file/d/1XNQw4KFCsF1sJhFdQPKGQfCAEu7-3cno/view?usp=drive_link",
        title: "BookishWear",
        desc: "Designed and developed an eCommerce platform for a book-themed clothing store.",
        stack: "React, NodeJs, ExpressJs, MongoDB, Redux",
        githubLink: "https://github.com/badalchowdhary/bookishwear_v2",
        webLink: "https://bookishwear-client.vercel.app/",
    },
    {
        id: 4,
        img: "https://drive.google.com/file/d/1XNQw4KFCsF1sJhFdQPKGQfCAEu7-3cno/view?usp=drive_link",
        title: "Pathfinder",
        desc: "Pathfinder is a pathfinding project which uses Dijkstra's Algorithm to find the shortest path.",
        stack: "React, Javascript",
        githubLink: "https://github.com/badalchowdhary/Pathfinder",
        webLink: "https://pathfinder-badal-chowdharys-projects.vercel.app/",
    },
    {
        id: 5,
        img: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A678%2F0*kxPYwfJmkXZ3iCWy.png&tbnid=INNC8jZSUNgFqM&vet=12ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy..i&imgrefurl=https%3A%2F%2Filolo.medium.com%2Funderstanding-the-mern-stack-for-full-stack-development-d8c6978b5ecb&docid=SxQZC2neo9uZGM&w=678&h=370&q=mern%20stack%20image&ved=2ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy",
        title: "NEEV Management System",
        desc: "Designed and developed database management system using SQL for NEEV.",
        stack: "SQL",
        githubLink: "https://github.com/badalchowdhary/Neev-webapplication",
        webLink: "",
    },
    {
        id: 6,
        img: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A678%2F0*kxPYwfJmkXZ3iCWy.png&tbnid=INNC8jZSUNgFqM&vet=12ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy..i&imgrefurl=https%3A%2F%2Filolo.medium.com%2Funderstanding-the-mern-stack-for-full-stack-development-d8c6978b5ecb&docid=SxQZC2neo9uZGM&w=678&h=370&q=mern%20stack%20image&ved=2ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy",
        title: "Image Analysis of Plant Based Meat Products",
        desc: "Carried out research about Image and Texture Analysis of plant based meat products analogues.",
        stack: "Python",
        githubLink: "https://github.com/badalchowdhary/Food_Recognition",
        webLink: "",
    },
    {
        id: 7,
        img: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A678%2F0*kxPYwfJmkXZ3iCWy.png&tbnid=INNC8jZSUNgFqM&vet=12ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy..i&imgrefurl=https%3A%2F%2Filolo.medium.com%2Funderstanding-the-mern-stack-for-full-stack-development-d8c6978b5ecb&docid=SxQZC2neo9uZGM&w=678&h=370&q=mern%20stack%20image&ved=2ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy",
        title: "House Price Prediction",
        desc: "Developed a machine learning model to predict the house prices in India.",
        stack: "Python",
        githubLink: "https://github.com/badalchowdhary/HousePrice_Prediction",
        webLink: "",
    },
    {
        id: 8,
        img: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A678%2F0*kxPYwfJmkXZ3iCWy.png&tbnid=INNC8jZSUNgFqM&vet=12ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy..i&imgrefurl=https%3A%2F%2Filolo.medium.com%2Funderstanding-the-mern-stack-for-full-stack-development-d8c6978b5ecb&docid=SxQZC2neo9uZGM&w=678&h=370&q=mern%20stack%20image&ved=2ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy",
        title: "PDC Website",
        desc: "Designed and developed the website of PDC council as a part of Hackrush'23.",
        stack: "ReactJs",
        githubLink: "https://github.com/badalchowdhary/hackrush-23_pdc-website",
        webLink: "https://badalchowdhary.github.io/hackrush-23_pdc-website/",
    },
    {
        id: 9,
        img: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A678%2F0*kxPYwfJmkXZ3iCWy.png&tbnid=INNC8jZSUNgFqM&vet=12ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy..i&imgrefurl=https%3A%2F%2Filolo.medium.com%2Funderstanding-the-mern-stack-for-full-stack-development-d8c6978b5ecb&docid=SxQZC2neo9uZGM&w=678&h=370&q=mern%20stack%20image&ved=2ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy",
        title: "CashWise",
        desc: "Developed a flutter application to track day-to-day expenses of a user.",
        stack: "Flutter, Dart",
        githubLink: "https://github.com/badalchowdhary/CashWise",
        webLink: "",
    },
    {
        id: 10,
        img: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A678%2F0*kxPYwfJmkXZ3iCWy.png&tbnid=INNC8jZSUNgFqM&vet=12ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy..i&imgrefurl=https%3A%2F%2Filolo.medium.com%2Funderstanding-the-mern-stack-for-full-stack-development-d8c6978b5ecb&docid=SxQZC2neo9uZGM&w=678&h=370&q=mern%20stack%20image&ved=2ahUKEwjY-a7D3fCEAxXrxjgGHYiMAugQMygBegQIARBy",
        title: "CipherSafe",
        desc: "Developed a flutter application where users can store their login credentials for different websites and apps.",
        stack: "Flutter, Dart",
        githubLink: "https://github.com/badalchowdhary/Cipher-Safe",
        webLink: "",
    }
];
